### ISSUE TITLE
Should we make a collective library in Zotero?

### ISSUE THREAD

**Issue by KatyaAplonova** [KatyaAplonova/ReportedDiscourseProject#21]
What do you think? We use it for Mande and that saves A LOT of time. You can import items from bibtex, so if you already have large bibliography files there, it will be fine.

**Comment by rvoll** [comment]
Yes! Sounds like a good plan!

**Comment by IndianaTones** [comment]
I am re-opening this issue to ask if, now that we have the shared [Zotero folder](https://www.zotero.org/groups/2379626/reporteddiscourseproject) is it possible to upload pdf's there?

Specifically, @rvoll, I know you were recently trying to get ahold of [Reported Discourse: A meeting ground for different linguistic domains](https://benjamins.com/catalog/tsl.52). Were you able to do so? If not, does someone else have access and could share it? 

@rvoll you also tried to send around a couple of other readings. If it is deemed possible to add pdf's to Zotero, could you upload them please?

**Comment by rvoll** [comment]
Hi Abbie! Indeed, I'd been looking for this article a year ago and I do have it now. As far as I know, it is possible to upload articles to Zotero now - or rather to myCore and to link Zotero to it. I will send you the file as an attachment for now, just in case you want it quick, because I haven't figured out how it works with Zotero, etc. But I will figure it out and upload it myself... Once I've figured it out I can also tell you or whoever is interested how it works.

**Comment by IndianaTones** [comment]
Thank you!!!

**Comment by IndianaTones** [comment]
Alright - should be working now :)  https://www.zotero.org/groups/2379626/reporteddiscourseproject/items/itemKey/WJDNMZK3

**Comment by rvoll** [comment]
Thanks Abbie! I've managed to upload another article to MyCore but have struggled fr an hour to add it to Zotero. In case you have a quick solution - I would be very grateful - but don't bother if it involves any effort!

**Comment by rvoll** [comment]
I have uploaded a text file with instructions on how to add literature to ZOTERO. Thanks to Becky for explaining it to me! Whoever wants to do it in the future can use my manual. Feel free to contact me if you still have problems.

**Comment by rvoll** [comment]
The file bears teh self-explanatory name "How to add literature to Zotero"
