### ISSUE TITLE
ELAN Q & A Session 2

### ISSUE THREAD

**Issue by IndianaTones** [KatyaAplonova/ReportedDiscourseProject#44]
Hi Folks,

As I believe it was very productive to hold the ELAN session during our last meeting, I am happy to do so again this coming week - Thursday or Friday - as people are available. 

Please do as Rebecca did and make a list of your questions so that we can try to solve them together during the session. 

:)

**Comment by Avamuru** [comment]
I'm not available to be at the office on Thursday or Friday this week, and I will likely be traveling the following week. And I understand that Tuesday and Wednesday will be full with meetings with Timofey. I would be grateful though if the ELAN session happens, that the Q&A are added to the wiki page started last time.
Thanks.

**Comment by IndianaTones** [comment]
Monday is also an option for me at least if others prefer.

**Comment by LacinaSilue** [comment]
Great idea ! Unfortunately, I will not be available on Monday, Tuesday and Thursday. Wednesday or Friday could be good for me.

**Comment by rvoll** [comment]
Hi guys!
I'll also be there on Tuesday afternoon and Wednesday until noon/early afternoon only. Why don't we do a multiparticipant skype meeting towards the end of next week or early the week after that? 
I could start a when2meet so we find a time suitable for everyone. Maybe that makes more sense because the time WILL be short on Tue & Wed. And yes, Becky - we'll add all ELAN Q&As to the Github Wiki! 
As for myself, thanks to the very helpful session last time!!! I am kind of satiated for now but I'm sure stuff will keep coming up and I'll probably have more questions by the end of next week...

**Comment by TanyaNikitina** [comment]
I am interested in easy ways to get stats for the distribution of all sorts of categories between Discourse Reports and everything that is not annotated as part of a discourse reporting construction. It would be really useful to have some kind of a generalized search where one could just specify the particular variable (part of speech, a word, etc.) and get the distribution quickly.

**Comment by rvoll** [comment]
As a couple of people have expressed in a second ELAN QnA session, I have created a when2meet where each of you can fill in which times would work for you to hold an online meeting via skype or so. Please fill in when you are available. If you are not interested, maybe write me a short note. Thanks!
This is the link:
https://www.when2meet.com/?8384348-izTxm

**Comment by rvoll** [comment]
Thanks for entering your preferred times! There are no times where everyone (th 6 people who signed up) is available at the same time. The two optimal options (4 people available out of 6) are today at 2:30-3pm: Abbie, Becky, Rebecca and Lacina are available, or next Monday between 1:30 and 3pm: Abbie, Becky, Rebecca and Katya. Tanya is available at neither of these times. 

1. @TanyaNikitina: Tanya, are you keen on joining or is it okay for you if we do this without you?
2. @LacinaSilue and @KatyaAplonova: do you need/want this QnA session right now? Just to figure out who of you two needs/wants it more so we can choose between today and next monday...

**Comment by TanyaNikitina** [comment]
Hi Rebecca, thanks for organizing this! Please go ahead and do it without me this time. If you think you could take some notes, that would be really useful to me as well!

**Comment by LacinaSilue** [comment]
> Thanks for entering your preferred times! There are no times where everyone (th 6 people who signed up) is available at the same time. The two optimal options (4 people available out of 6) are today at 2:30-3pm: Abbie, Becky, Rebecca and Lacina are available, or next Monday between 1:30 and 3pm: Abbie, Becky, Rebecca and Katya. Tanya is available at neither of these times.
> 
> 1. @TanyaNikitina: Tanya, are you keen on joining or is it okay for you if we do this without you?
> 2. @LacinaSilue and @KatyaAplonova: do you need/want this QnA session right now? Just to figure out who of you two needs/wants it more so we can choose between today and next monday...

I

**Comment by LacinaSilue** [comment]
Hi all, it seems I had closed the issue by mistake. Sorry for this.

**Comment by rvoll** [comment]
Hi Tanya! Thanks for the note! Yes. We will take notes and enter relevant stuff into the ELAN Wiki that Becky created.

**Comment by rvoll** [comment]
Hi Lacina! 
Any question you have is worth asking!
Unless maybe those that you can answer yourself but even that is often hard to tell...
Concerning your issue 1: 
I think Abbie was gonna assemble a list of tier names and descriptions - 
@IndianaTones or did I make this up? Not sure whether it is online, yet. I don't think.
@IndianaTones - in case it still needs work, can I help with this? 
It would be very useful to everyone.

Concerning your issue 2: you certainly have a point and it involves some effort to do teh cutting, esp. if you cut audio and video and want to align them.
@all: How about whoever has time, gets online at 2:30 to answer Lacina's question number 2?!
i.e., Abbie, Becky, me and Lacina - we chat for a bit, and then we discuss the questions of everyone else on Monday?

**Comment by rvoll** [comment]
I found this 
https://videolink2me.com/start
as an alternative to Skype in case skype doesn't work for some of us. I'll try to get it ging before 2:30.

**Comment by rvoll** [comment]
Let's try to skype! Lacina said his skype is working now. So we discuss his issue now - and the actual 
ELAN QnA skype session will take place on Monday at 2pm!
I'll enter it in the calendar.

**Comment by rvoll** [comment]
We have already discussed Lacina's questions but once more for the record: 
1. the template and tier descriptions:
I am planning to complement the tier descriptions that Abbie uploaded into the folder EXAMPLES OF ANNOTATED FILES in order to make them more transparent

2.  about cutting up audio and video files and which files to use for ELAN transcription: 

Ideally, try to use the video files right fom the beginning when you annotate with ELAN! Using the videos right from the start will save you a lot of work, because you - or much rather Franck - can use the original video file and lay it over with the sound. This it is much easier to create the final ELAN file with video than if you do it the other way round - which may never render a perfect result. So this is what you should do: 
Take your sound and video recording(s) of the 60 minute multiple story session, ask Franck to sync/overlay them if necessary (i.e. when the sound from the audio is much better than that of your video recording); then ask him to cut up the amalgamated video file at the story boundaries; start transcribing in ELAN ideally only once you have the video files you can work with! 
If you already have started transcribing audio files but want the final result to be transcribed video eaf files - there is a way to do this but it is much more work and may not render a perfect result...

**Comment by IndianaTones** [comment]
That's great @rvoll but before you duplicate work do check out our Wiki page - https://github.com/KatyaAplonova/ReportedDiscourseProject/wiki/SR-Template

**Comment by LacinaSilue** [comment]
Thanks Abbie,

My concern is partially settled.

Le jeu. 14 nov. 2019 à 14:11, Abbie Hantgan <notifications@github.com> a
écrit :

**Comment by IndianaTones** [comment]
Just a reminder that I'll be looking forward to seeing anyone who has ELAN issues (that I can hopefully help with) at 14:00 today on Skype. 🥇
